---
- name: Check status of Site24x7 server monitoring agent
  hosts: all
  become_method: sudo
  
  tasks:
     - name: Checking status of Site24x7 monitoring agent
       shell: /etc/init.d/site24x7monagent status
       register: checkInstallSite24x7
       ignore_errors: yes