---
- name: Restart Site24x7 server monitoring agent
  hosts: all
  
  tasks:
     - name: Restart Site24x7 monitoring agent
       shell: /etc/init.d/site24x7monagent restart
       register: checkInstallSite24x7
       ignore_errors: yes